import { randomUUID } from 'node:crypto';

import type { StringType } from '@driimus/dynamodb-data-marshaller';

import type { PropertyAnnotation } from './annotationShapes';
import { hashKey } from './hashKey';

export function autoGeneratedHashKey(parameters: Partial<StringType> = {}): PropertyAnnotation {
  return hashKey({
    ...parameters,
    type: 'String',
    defaultProvider: randomUUID,
  });
}
