import {randomUUID} from 'node:crypto';
import {StringType} from '@aws/dynamodb-data-marshaller';
import {PropertyAnnotation} from './annotationShapes';
import {hashKey} from './hashKey';

export function autoGeneratedHashKey(
	parameters: Partial<StringType> = {},
): PropertyAnnotation {
	return hashKey({
		...parameters,
		type: 'String',
		defaultProvider: randomUUID,
	});
}
